### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by manisoni28**
Updated Screenshots in Readme to make UI more attractive

### CODE REVIEW

**Comment by manisoni28** [comment]
Changed background name

**Comment by RajuKoushik** [comment]
The Floating Edit Text could be implemented and looks much better @manisoni28 . Just create a new branch and then send a pull request. The pull request would then be scrutinized and merged.Cheers.

**Comment by manisoni28** [comment]
Yoo bro.It will be done by today evening..

**Comment by RajuKoushik** [comment]
Cool. @manisoni28  Keep Going. :)

**Pull request merged**
